src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="product")
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 */
class Product
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", name="name")
     */
    private $name;

    /**
     * @ORM\Column(type="string", name="slug")
     */
    private $slug;

    /**
     * @ORM\Column(type="text", name="summary")
     */
    private $summary;

    /**
     * @ORM\Column(type="text", name="description")
     */
    private $description;

    /**
     * @ORM\Column(type="string", name="reference")
     */
    private $reference;

    /**
     * @ORM\Column(type="integer", name="quantity")
     */
    private $quantity;

    /**
     * @ORM\Column(type="integer", name="quantity_in_cart", nullable=true)
     */
    private $quantity_in_cart;

    /**
     * @ORM\Column(type="float", name="price_ht")
     */
    private $priceHt;

    /**
     * @ORM\Column(type="float", name="price_ttc", nullable=true)
     */
    private $priceTtc;

    /**
     * @ORM\Column(type="datetime", name="date_creation")
     */
    private $date_creation;

    /**
     * Many Features have One Product.
     * @ORM\Column(type="integer", name="category", nullable=true)
     */
    private $category;

    /**
     * @ORM\Column(type="string", name="image")
     */
    private $image;

    /**
     * @ORM\Column(type="float", name="tva")
     */
    private $tva;

    public function __construct()
    {
        $this->date_creation = new \DateTime();
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param integer $id
     */
    public function setId($id): void
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param mixed $name
     */
    public function setName($name): void
    {
        $this->name = $name;
    }

    /**
     * @return mixed
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * @param string $slug
     */
    public function setSlug($slug): void
    {
        $this->slug = $slug;
    }

    /**
     * @return mixed
     */
    public function getSummary()
    {
        return $this->summary;
    }

    /**
     * @param string $summary
     */
    public function setSummary($summary): void
    {
        $this->summary = $summary;
    }

    /**
     * @return mixed
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param string $description
     */
    public function setDescription($description): void
    {
        $this->description = $description;
    }

    /**
     * @return mixed
     */
    public function getReference()
    {
        return $this->reference;
    }

    /**
     * @param string $reference
     */
    public function setReference($reference): void
    {
        $this->reference = $reference;
    }

    /**
     * @return mixed
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * @param integer $quantity
     */
    public function setQuantity($quantity): void
    {
        $this->quantity = $quantity;
    }

    /**
     * @return mixed
     */
    public function getQuantityInCart()
    {
        return $this->quantity_in_cart;
    }

    /**
     * @param mixed $quantity_in_cart
     */
    public function setQuantityInCart($quantity_in_cart): void
    {
        $this->quantity_in_cart = $quantity_in_cart;
    }

    /**
     * @return mixed
     */
    public function getPriceHt()
    {
        return $this->priceHt;
    }

    /**
     * @param float $priceHt
     */
    public function setPriceHt($priceHt): void
    {
        $this->priceHt = $priceHt;
    }

    /**
     * @return mixed
     */
    public function getPriceTtc()
    {
        return $this->priceTtc;
    }

    /**
     * @param float $priceTtc
     */
    public function setPriceTtc($priceTtc): void
    {
        $this->priceTtc = $priceTtc;
    }

    /**
     * @return mixed
     */
    public function getDateCreation()
    {
        return $this->date_creation;
    }

    /**
     * @param \DateTime $date_creation
     */
    public function setDateCreation($date_creation): void
    {
        $this->date_creation = $date_creation;
    }

    /**
     * @return mixed
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * @param integer $category
     */
    public function setCategory($category)
    {
        $this->category = $category;
    }

    /**
     * @return mixed
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * @param string $image
     */
    public function setImage($image): void
    {
        $this->image = $image;
    }

    /**
     * @return mixed
     */
    public function getTva()
    {
        return $this->tva;
    }

    /**
     * @param float $tva
     */
    public function setTva($tva): void
    {
        $this->tva = $tva;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Table(name="user")
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface, \Serializable
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", name="email")
     */
    private $email;

    /**
     * @ORM\Column(type="string", name="username")
     */
    private $username;

    /**
     * @ORM\Column(type="string", name="password")
     */
    private $password;

    /**
     * @ORM\Column(type="boolean", name="active")
     */
    private $active;

    /**
     * @ORM\Column(type="array", name="roles")
     */
    private $roles;

    /**
     * @ORM\Column(type="string", name="token")
     */
    private $token;

    /**
     * One User has Many Addresses.
     * @ORM\Column(type="array", name="addresses")
     * @ORM\OneToMany(targetEntity="App\Entity\UserAddress", mappedBy="user")
     */
    private $addresses;

    /**
     * One User has One Panier.
     * @ORM\OneToOne(targetEntity="App\Entity\Panier", mappedBy="user")
     */
    private $panier;

    /**
     * One User has Many Orderings.
     * @ORM\OneToMany(targetEntity="App\Entity\Ordering", mappedBy="user")
     */
    private $orderings;


    public function __construct()
    {
        $this->active = false;
        $this->roles = ['ROLE_USER'];
        $this->addresses = new ArrayCollection();
        $this->orderings = new ArrayCollection();
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param integer $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * @param string $email
     */
    public function setEmail($email)
    {
        $this->email = $email;
    }

    public function getUsername()
    {
        return $this->username;
    }

    public function setUsername($username)
    {
        $this->username = $username;
    }

    /**
     * @return mixed
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password = $password;
    }

    /**
     * @return mixed
     */
    public function getActive()
    {
        return $this->active;
    }

    /**
     * @param boolean $active
     */
    public function setActive($active)
    {
        $this->active = $active;
    }

    /**
     * @return mixed
     */
    public function getRoles()
    {
        return $this->roles;
    }

    /**
     * @param array $roles
     */
    public function setRoles($roles)
    {
        $this->roles = $roles;
    }

    /**
     * @return mixed
     */
    public function getToken()
    {
        return $this->token;
    }

    public function setToken()
    {
        $this->token = md5(uniqid("token_", true));
    }

    public function resetToken()
    {
        $this->token = '';
    }

    /**
     * @return mixed
     */
    public function getAddresses()
    {
        return $this->addresses;
    }

    /**
     * @param mixed $addresses
     */
    public function setAddresses($addresses)
    {
        $this->addresses = $addresses;
    }

    /**
     * @param UserAddress $address
     */
    public function addAddress(UserAddress $address)
    {
        $this->addresses[] = $address;
    }

    /**
     * @return mixed
     */
    public function getPanier()
    {
        return $this->panier;
    }

    /**
     * @param mixed $panier
     */
    public function setPanier($panier)
    {
        $this->panier = $panier;
    }

    /**
     * @return mixed
     */
    public function getOrderings()
    {
        return $this->orderings;
    }

    /**
     * @param mixed $orderings
     */
    public function setOrderings($orderings)
    {
        $this->orderings = $orderings;
    }


    public function eraseCredentials()
    {
    }

    public function __toString()
    {
        return (string)$this->username;
    }

    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->username,
            $this->password,
            // see section on salt below
            // $this->salt,
        ));
    }

    /** @see \Serializable::unserialize() */
    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->username,
            $this->password,
            // see section on salt below
            // $this->salt
            ) = unserialize($serialized);
    }

    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }
}

src/Entity/UserAddress.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="user_address")
 * @ORM\Entity(repositoryClass="App\Repository\UserAddressRepository")
 */
class UserAddress
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", name="street")
     */
    private $street;

    /**
     * @ORM\Column(type="string", name="complement", nullable=true)
     */
    private $complement;

    /**
     * @ORM\Column(type="string", name="code_postal")
     */
    private $code_postal;

    /**
     * @ORM\Column(type="string", name="city")
     */
    private $city;

    /**
     * @ORM\Column(type="string", name="country")
     */
    private $country;

    /**
     * @ORM\Column(type="string", name="type")
     */
    private $type;

    /**
     * @ORM\Column(type="string", name="full")
     */
    private $full;

    /**
     * Many Addresses have One User.
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="user_address", cascade={"persist"})
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    private $user;

    public function __construct(User $user)
    {
        $this->user = $user;
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id): void
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getStreet()
    {
        return $this->street;
    }

    /**
     * @param mixed $street
     */
    public function setStreet($street): void
    {
        $this->street = $street;
    }

    /**
     * @return mixed
     */
    public function getComplement()
    {
        return $this->complement;
    }

    /**
     * @param mixed $complement
     */
    public function setComplement($complement): void
    {
        $this->complement = $complement;
    }

    /**
     * @return mixed
     */
    public function getCodePostal()
    {
        return $this->code_postal;
    }

    /**
     * @param mixed $code_postal
     */
    public function setCodePostal($code_postal): void
    {
        $this->code_postal = $code_postal;
    }

    /**
     * @return mixed
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * @param mixed $city
     */
    public function setCity($city): void
    {
        $this->city = $city;
    }

    /**
     * @return mixed
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * @param mixed $country
     */
    public function setCountry($country): void
    {
        $this->country = $country;
    }

    /**
     * @return mixed
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @param string $type
     */
    public function setType($type)
    {
        $this->type = $type;
    }

    /**
     * @return mixed
     */
    public function getFull()
    {
        return $this->full;
    }

    /**
     * @param string $full
     */
    public function setFull($full): void
    {
        $this->full = $full;
    }

    /**
     * @return mixed
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param mixed $user
     */
    public function setUser($user)
    {
        $this->user = $user;
    }

    public function __toString()
    {
        return (string)$this->street;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'email',
                EmailType::class
            )
            ->add(
                'password',
                PasswordType::class
            )
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            // uncomment if you want to bind to a class
            'data_class' => User::class,
        ]);
    }
}

src/Controller/Admin/UserController.php
<?php

namespace App\Controller\Admin;

use App\Entity\User;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class UserController extends Controller
{
    /**
     * @Route("/admin/users", name="admin_user_list")
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function list()
    {
        $users = $this->getDoctrine()->getRepository(User::class)->findAll();
        return $this->render(
            'admin/user/list.html.twig',
            array(
                'users' => $users
            )
        );
    }
}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {{ controller_name }}!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code>src/Controller/UserController.php</code></li>
        <li>Your template at <code>templates/user/index.html.twig</code></li>
    </ul>
</div>
{% endblock %}

templates/user/payment.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <section class="container">
        <div class="row">
            <div class="col-xs-12 card">
                <h1>Paiement</h1>
                {{ dump(order) }}
            </div>
        </div>
        <div class="row">
            <div class="col-lg-3">
                <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                    <a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="#v-pills-home" role="tab" aria-controls="v-pills-home" aria-selected="true">Payer avec PayPal</a>
                    <a class="nav-link" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-profile" role="tab" aria-controls="v-pills-profile" aria-selected="false">Payer avec Stripe</a>
                    <a class="nav-link" id="v-pills-messages-tab" data-toggle="pill" href="#v-pills-messages" role="tab" aria-controls="v-pills-messages" aria-selected="false">Payer par virement bancaire</a>
                    <a class="nav-link" id="v-pills-settings-tab" data-toggle="pill" href="#v-pills-settings" role="tab" aria-controls="v-pills-settings" aria-selected="false">Payer par carte bancaire</a>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="tab-content" id="v-pills-tabContent">
                    <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
                        <a href="{{ path('payment_accepted', {'id': panier.id}) }}" class="btn btn-primary">Payer</a>
                    </div>
                    <div class="tab-pane fade" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">
                        <a href="{{ path('payment_accepted', {'id': panier.id}) }}" class="btn btn-primary">Payer</a>
                    </div>
                    <div class="tab-pane fade" id="v-pills-messages" role="tabpanel" aria-labelledby="v-pills-messages-tab">
                        <a href="{{ path('payment_accepted', {'id': panier.id}) }}" class="btn btn-primary">Payer</a>
                    </div>
                    <div class="tab-pane fade" id="v-pills-settings" role="tabpanel" aria-labelledby="v-pills-settings-tab">
                        <a href="{{ path('payment_accepted', {'id': panier.id}) }}" class="btn btn-primary">Payer</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/user/payment_accepted.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h1 class="page-header text-center">Paiement accepté ! Merci pour votre commande</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                {{ dump(ordering) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/user/user_info.html.twig
{% extends "base2.html.twig" %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                {{ form_start(panier_form) }}
                <fieldset class="form-group">
                    {{ form_row(panier_form.livraison) }}
                </fieldset>
                <fieldset class="form-group">
                    {{ form_row(panier_form.facturation) }}
                </fieldset>
                <fieldset class="form-group">
                    <button type="submit" class="btn btn-primary">Valider mes adresses</button>
                </fieldset>
                {{ form_end(panier_form) }}
            </div>
            <div class="col-lg-6">
                <h2>Ajouter une adresse</h2>
                {{ form_start(form) }}
                <fieldset>
                    {{ form_label(form.type) }}
                    {{ form_widget(form.type) }}
                </fieldset>
                <fieldset>
                    {{ form_label(form.street) }}
                    {{ form_widget(form.street) }}
                </fieldset>
                <fieldset>
                    {{ form_label(form.complement) }}
                    {{ form_widget(form.complement) }}
                </fieldset>
                <fieldset>
                    {{ form_label(form.codePostal) }}
                    {{ form_widget(form.codePostal) }}
                </fieldset>
                <fieldset>
                    {{ form_label(form.city) }}
                    {{ form_widget(form.city) }}
                </fieldset>
                <fieldset>
                    {{ form_label(form.country) }}
                    {{ form_widget(form.country) }}
                </fieldset>
                <fieldset>
                    <button type="submit" class="btn btn-primary">Ajouter</button>
                </fieldset>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/user/validate_user_info.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <section class="container">
        <div class="row">
            <div class="col-xs-12">
                <h1 class="page-header">Votre commande</h1>
            </div>
        </div>
        {% if panier is defined %}
            <div class="row">
                <div class="col-lg-6">
                    <h2>Vos informations</h2>
                    <p>
                        Email: {{ panier.user.email }}
                    </p>
                    <p>
                        Livraison: {{ panier.livraison }}
                    </p>
                    <p>
                        Facturation: {{ panier.facturation }}
                    </p>
                </div>
                <div class="col-lg-6">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Image</th>
                            <th>Nom</th>
                            <th>Tarif HT</th>
                            <th>TVA</th>
                            <th>Quantité disponible</th>
                            <th>Quantité en panier</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for product in panier.products %}
                            <tr>
                                <td>
                                    <img src="{{ product.image }}" alt="{{ product.name }}" height="50">
                                </td>
                                <td>
                                    <h2>{{ product.name }}</h2>
                                </td>
                                <td>
                                    {{ product.priceHt }} €
                                </td>
                                <td>
                                    {{ product.tva*100 }}%
                                </td>
                                <td>
                                    {{ product.quantity }}
                                </td>
                                <td>
                                    {{ product.quantityInCart }}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="col-xs-12">
                    <a href="{{ path('pay') }}">Valider ma commande et payer</a>
                </div>
            </div>
        {% endif %}
    </section>
{% endblock %}